name: PR Source Code Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - run: cd frontend && yarn
      - run: cd frontend && yarn lint:strict

  tsc:
    name: Run Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - run: cd frontend && yarn
      - run: cd frontend && yarn tsc

  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - run: cd frontend && yarn
      - run: cd frontend && yarn prettier:check

  
  server:
    name: Run Build and Test the Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build GO Server
        run: cd server && go build -v ./...

      - name: Test Go Server
        run: cd server && go test -v ./...
      
